# Generated by Django 4.1 on 2023-07-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbooks',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
