# Generated by Django 4.1 on 2023-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_listofbooks_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofbooks',
            name='slug',
            field=models.SlugField(default='empty', max_length=250, unique=True),
        ),
    ]
